title: Jatin Kumar
logo: docs/assets/240E23FF-DAE0-44CE-9614-9E061BB7C0E5_1_105_c.jpeg
description: Aspiring Software Engineer

theme: jekyll-theme-minimal

<link rel="stylesheet" href="/docs/styles.css">

